// jib에서 spring boot + docker 플러그인 무시하게
buildscript {
    dependencies {
        classpath('com.google.cloud.tools:jib-layer-filter-extension-gradle:0.3.0')
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
    // Docker 이미지를 만들어서 (쉽게?) 서버에 올리기 위한 빌드업
    // 구글에서 만든 'jib'이라 불리는 플러그인을 사용합니다. 빌드스크립트에 기능을 추가하는 플러그인이지요
    id 'com.google.cloud.tools.jib' version '3.5.3'
}

group = 'team2.mse.ajou'
version = '0.0.1-SNAPSHOT'
description = 'ajou-mse-server'

// jib 플러그인을 셋팅해봅시다
jib {
    to {
        image = 'ajou-mse/server'
    }

    container {
        ports = [ '8080/tcp' ];
    }

    // docker compose 플러그인 무시. 어쩌피 docker에서 실행하니깐 spring boot 플러그인으로 별도로 실행해줄 필요가 없습니다
    pluginExtensions {
        pluginExtension {
            implementation = 'com.google.cloud.tools.jib.gradle.extension.layerfilter.JibLayerFilterExtension'
            configuration {
                filters {
                    filter {
                        glob = '**/spring-boot-docker-compose-*.jar'
                    }
                }
            }
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
//    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
//    testImplementation 'org.testcontainers:mysql'
    compileOnly 'org.projectlombok:lombok'
//    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
//    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

// Docker에 사용 가능한 secrets 파일 생성
tasks.register('generateDockerSecrets') {
    doLast {
        def dir = layout.buildDirectory.get().asFile
        dir.mkdirs()

        def mysql_root_password = "test"
        def mysql_username = "test"
        def mysql_password = "test"

        def props = new Properties()
        props.load(project.rootProject.file("src/main/resources/application-secrets.properties").newReader())

        mysql_username = props.getProperty("spring.datasource.username", mysql_username)
        mysql_password = props.getProperty("spring.datasource.password", mysql_password)

        new File(dir, "mysql_root_password.txt").text = mysql_root_password
        new File(dir, "mysql_user.txt").text = mysql_username
        new File(dir, "mysql_password.txt").text = mysql_password
    }
}

tasks.named('classes').configure {
    dependsOn 'generateDockerSecrets'
}