# Docker compose setup file.
# Ahn Yubin / 202021088
services:
  mysql-db:
    image: mysql
    container_name: mse-2026-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/SECRET_MYSQL_ROOT_PASSWORD
      MYSQL_USER_FILE: /run/secrets/SECRET_MYSQL_USER
      MYSQL_PASSWORD_FILE: /run/secrets/SECRET_MYSQL_PASSWORD
      MYSQL_DATABASE: ajou_mse_2026
    secrets:
      - SECRET_MYSQL_ROOT_PASSWORD
      - SECRET_MYSQL_USER
      - SECRET_MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone:ro
#    networks:
#      - ajou-mse-2026-backend
    healthcheck: # Wait for MySQL to run
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$(cat /run/secrets/SECRET_MYSQL_USER)", "-p$$(cat /run/secrets/SECRET_MYSQL_PASSWORD)" ]
      interval: 10s
      retries: 5
      start_period: 20s

  mse-server:
    container_name: mse-2026-backend
    profiles:
      - deploy
    depends_on:
      mysql-db:
        condition: service_healthy
    image: ajou-mse/server
    tty: true
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone:ro
    environment:
      MYSQL_HOST: mse-2026-mysql-db
secrets:
  SECRET_MYSQL_ROOT_PASSWORD:
    file: ./build/mysql_root_password.txt
  SECRET_MYSQL_USER:
    file: ./build/mysql_user.txt
  SECRET_MYSQL_PASSWORD:
    file: ./build/mysql_password.txt
#    networks:
#      - ajou-mse-2026-backend