services:
  mysql-db:
    image: mysql
    container_name: mse-2026-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mse2026rt
      MYSQL_USER: mse2026
      MYSQL_PASSWORD: mse2026
      MYSQL_DATABASE: ajou_mse_2026
    ports:
      - "3306:3306"
#    networks:
#      - ajou-mse-2026-backend
    healthcheck: # MySQL이 정상적으로 실행될 때까지 기다리도록 설정
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-umse2026", "-pmse2026" ]
      interval: 10s
      retries: 5
      start_period: 20s

  mse-server:
    container_name: mse-2026-backend
    profiles:
      - deploy
    depends_on:
      mysql-db:
        condition: service_healthy
    image: ajou-mse/server
    tty: true
    restart: always
    ports:
      - "8080:8080"
#    networks:
#      - ajou-mse-2026-backend