# DEVELOPMENT SERVER!
spring.application.name=ajou-mse-server-dev
# spring.profiles.active=dev

server.port=8088
server.servlet.context-path=/dev

# Docker
spring.docker.compose.profiles.active=dev-db

# Secret settings. All the values that are suppossed to be not exposed publicly are stored in `application.properties`.
spring.config.import=classpath:application-secrets-dev.properties