spring.application.name=ajou-mse-server

# Mysql 설정
# DB를 서버 시작시 DROP하게 시킵니다. 왜냐면 테스트가 많이 진행될 것 같은데 이전 서버 돌렸을 시점에 남은 데이터가 있으면 데이터까 꼬일 확률이 커서...
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Secret 설정. 여기에 MySQL 비밀번호나 API key 같은 설정을 넣어주시면 되겠습니다.
spring.profiles.include=secrets