spring.application.name=ajou-mse-server

# Mysql setup
# Force drop database on server startup to ensure consistent behaviour (FOR NOW - would be changed later!)
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true

# Secret settings. All the values that are suppossed to be not exposed publicly are stored in `application.properties`.
spring.profiles.include=secrets

# About Korean Formatting
server.servlet.encoding.force-response=true

#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.use-root-path=false
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
