spring.application.name=ajou-mse-server


# Mysql 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Secret 설정. 여기에 MySQL 비밀번호나 API key 같은 설정을 넣어주시면 되겠습니다.
spring.profiles.include=secrets

# About Korean Formatting
server.servlet.encoding.force-response=true

#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.use-root-path=false
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
