# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build with Gradle & Deploy to development environment

on:
  push:
    branches: [ "deploy-dev" ]
  pull_request:
    types: "closed"
    branches: [ "deploy-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Github Actions이 돌아가는 IP 가져오기
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Amazon EC2 접근 가능하게 AWS Credentials 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Amazon EC2에 Github Actions이 돌아가는 IP 넣기
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Application secret 생성
      run: |
        touch ./src/main/resources/application-secrets.properties
        echo 'spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ajou_mse_2026' >> ./src/main/resources/application-secrets.properties
        echo "spring.datasource.username=${{ secrets.SECRET_MYSQL_USER }}" >> ./src/main/resources/application-secrets.properties
        echo "spring.datasource.password=${{ secrets.SECRET_MYSQL_PASSWORD }}" >> ./src/main/resources/application-secrets.properties
        echo "external.api.key=${{ secrets.SECRET_SUBWAY_API_KEY }}" >> ./src/main/resources/application-secrets.properties

    - name: Firebase secret 생성
      run: |
        touch ./src/main/resources/ajou-mse-firebase-adminsdk-fbsvc-1dee6ea80f.json
        echo '${{ secrets.SECRET_FIREBASE_SERVICE_ACCOUNT }}' >> ./src/main/resources/ajou-mse-firebase-adminsdk-fbsvc-1dee6ea80f.json

    - name: application-secrets 파일 확인용 업로드
      uses: actions/upload-artifact@v4
      with:
        name: application-secrets
        path: ./src/main/resources/application-secrets.properties

    - name: Firebase secret 파일 확인용 업로드
      uses: actions/upload-artifact@v4
      with:
        name: firebase-secrets
        path: ./src/main/resources/ajou-mse-firebase-adminsdk-fbsvc-1dee6ea80f.json

    - name: JDK 25 설정하기
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Gradle (gradlew) 쓰기 전에 셋팅하기
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Gradle Wrapper로 프로젝트 빌드
      run: ./gradlew jibBuildTar -PIS_GITHUB_CI_CD=true
    
    # Amazon EC2 머신 상의 ~/deploy 폴더속에 넘깁니다. ( ~/deploy -> /home/dolce/deploy 로 단축 )
    - name: 빌드한 Docker (.tar 이미지 + docker-compose.yml) 파일 SCP로 EC2 머신에 넘기기
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: "dolce" # 이름이 돌쇠래요 껄껄껄
        key: ${{ secrets.SSH_KEY_DEPLOYMENT }}
        source: build/jib-image.tar, build/mysql_root_password.txt, build/mysql_user.txt, build/mysql_password.txt, docker-compose.yaml
        target: /home/dolce/deploys
    
    - name: EC2에 SSH로 접속해 실행하기
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: "dolce"
        key: ${{ secrets.SSH_KEY_DEPLOYMENT }}
        # ~/deploys 로 이동
        # docker에 받아온 이미지 파일 로드
        # docker compose로 docker-compose.yml 내용대로 docker 실행
        # 안쓰이는 이미지 파일 버리기
        script: |
          cd /home/dolce/deploys
          docker load -i ./build/jib-image.tar
          docker compose --profile deploy up -d
          docker image prune -f

    - name: Github Actions IP 제거 (원상복귀)
      # (중간에 빌드 삑사리나서 actions가 캔슬되어도 원상복귀는 계속되야합니다!!)
      if: ${{ always() }}
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

    - name: 빌드 파일 확인용 업로드
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./build/jib-image.tar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: JDK 25 설정하기
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
